# -*- coding: utf-8 -*-
"""LLM-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7FWZpzLl2MxCRK6pzW_f55vLsy3qIHM
"""

from transformers import pipeline
classifier = pipeline('sentiment-analysis')

classifier('I am very exited to teach the llm course')

classifier(['I am feeling happy today','I am feeling sad today'])

classifier = pipeline('zero-shot-classification')

classifier('PM of India is Narendra Modi',candidate_labels=['education','politics','entertainment'])

generator = pipeline('text-generation')

generator("PES University is ")

generator= pipeline('text-generation', model='distilgpt2')

generator('Bengaluru is ',max_length=30 , num_return_sequences=2)

unmasker=pipeline('fill-mask')
unmasker("PES University is in <mask>", top_k=2)

NER=pipeline('ner',grouped_entities=True)
NER("Shylaja is working in PES University, Bengaluru")

qa=pipeline('question-answering')
qa(question="What is my name",context='Shylaja works for pes university')

summarize=pipeline('summarization')
summarize("""Archaeological artifacts indicate that the human settlement in the region happened as early as 4000 BCE. The first mention of the name "Bengalooru" is from an old Kannada stone inscription from 890 CE found at the Nageshwara Temple. After having been ruled by the Western Ganga dynasty, from the beginning of the Common Era, the city became part of the Chola empire in the early eleventh century CE. The region was part of the Hoysala, and Vijayanagara Empire in the Late Middle Ages. In 1537 CE, Kempe Gowda I, a feudal ruler under the Vijayanagara Empire, established a mud fort, considered the foundation of the modern city of Bengaluru and its oldest areas, or petes, which still exist. After the fall of the Vijayanagara Empire, Kempe Gowda declared independence, and the city was expanded by his successors. In 1638 CE, a Adil Shahi army defeated Kempe Gowda III, and the city became a jagir (feudal estate) of Shahaji Bhonsle. The Mughals later captured Bengaluru and sold it to Maharaja Chikkadevaraja Wodeyar of the Kingdom of Mysore. After the death of Krishnaraja Wodeyar II in 1759 CE, Hyder Ali seized control of the kingdom, and the administration passed subsequently to his son Tipu Sultan.

The city was captured by the British East India Company during the Anglo-Mysore Wars, and became part of the Princely State of Mysore. The administrative control of the city was returned to Krishnaraja Wadiyar III, then Maharaja of Mysore, and the old city developed under the dominions of the Mysore kingdom. In 1809 CE, the British shifted their military garrison to the city and established the cantonment, outside the old city. In the late 19th century CE, the city was essentially composed of two distinct urban settlements, the old pete and the new cantonment. Following India's independence in 1947, Bengaluru became the capital of Mysore State, and remained the capital when the state was enlarged and unified in 1956 and subsequently renamed to Karnataka in 1973. The two urban settlements which had developed as independent entities, merged under a single urban administration in 1949. The city was officially known as Bangalore in English till 2006, The official name was changed to its Kannada name, "Bengaluru".""")